
name: CICD

on:

  push:
    branches: [ main, feature/add-ci-cd ]
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  azure_deploy:
    runs-on: ubuntu-latest
    environment: Staging
    steps:
      - uses: actions/checkout@v2
      
      - name: Diagnostics
        run: |
          pwd
          ls
      # curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

      # - name: Install jq
      #   run: sudo apt-get install jq

      - name: Replace parameter values in parameters.json
        run: |
          echo ===== Before ======
          cat 'src/parameters.json'
          jq '.parameters.connections_logicapp_keyvault_name.value |= "${{ secrets.AZ_RG_DV_CONNECTION_NAME }}"'  src/parameters.json >  src/parameters_new.json
          echo ====== After 1 ======
          cat 'src/parameters_new.json'
          jq '.parameters.vaults_key_vault_name.value |= "${{ secrets.AZ_RG_DV_KEYVAULT_NAME }}"' src/parameters_new.json >  src/parameters.json
          echo ====== After 2 ======
          cat 'src/parameters.json'
          jq '.parameters.workflows_lock_default_branch_name.value |= "${{ secrets.AZ_RG_DV_LOGICAPP_NAME }}"' src/parameters.json > src/parameters_new.json
          echo ====== After 3 ======
          cat 'src/parameters_new.json'
          jq '.parameters.strings_personal_access_token.value |= "${{ secrets.INTPLUS_GITHUB_APP_SECRET }}"' src/parameters_new.json >  src/parameters.json
          echo ====== After ======
          cat 'src/parameters.json'

      # Login to Azure
      - name: Azure Login
        run: az login --service-principal -u ${{ secrets.AZ_RG_DV_GITHUB_TEST_DEMO_CLIENT_ID }} -p ${{ secrets.AZ_RG_DV_GITHUB_TEST_DEMO }} --tenant ${{ secrets. AZ_RG_DV_TENANT_ID }}
      
      # Deploy template
      - name: Deploy Azure Resource Manager (ARM) Template
        run: az deployment group create --resource-group ${{ secrets.AZ_RG_DV_RESOURCE_GROUP }} --mode Incremental --parameters src/parameters.json --template-uri src/template.json

