# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      resource_group_name:
        description: 'Name of the resource group for the environment.'
        required: true
        type: string
        default: 'github-test-demo'
      location:
        description: 'Azure region to deploy to'
        type: string
        default: 'australiasoutheast'
      subscription_id:
        description: 'Azure subscription id'
        required: true
        type: string
      keyvault_name:
        description: 'Name of the Azure Key Vault resource'
        required: true
        type: string
      logic_app_name:
        description: 'Name of the Logic App web API resource'
        required: true
        type: string
        
env:
  keyvault_logicapp_connection: kv-la-conn

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  azure_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # - name: Install jq
      #   run: sudo apt-get install jq

      - name: Replace parameter values in parameters.json
        run: |
          echo ===== Before ======
          cat '$GITHUB_WORKSPACE/src/parameters.json'
          jq '.parameters.connections_logicapp_keyvault_name.value |= "$keyvault_logicapp_connection"' $GITHUB_WORKSPACE/src/parameters.json
          jq '.parameters.vaults_key_vault_name.value |= "$keyvault_name"' $GITHUB_WORKSPACE/src/parameters.json
          jq '.parameters.workflows_lock_default_branch_name.value |= "$logic_app_name"' $GITHUB_WORKSPACE/src/parameters.json
          jq '.parameters.strings_personal_access_token.value |= "${{ secrets.GITHUB_APP_SECRET }}"' $GITHUB_WORKSPACE/src/parameters.json
          echo ====== After ======
          cat '$GITHUB_WORKSPACE/src/parameters.json'

      # Login to Azure
      - name: Azure Login
        uses: Azure/login@v1.4.3
        with:
          # Secret of the Azure Service principal
          creds: ${{ secrets.AZ_RG_DV_GITHUB_TEST_DEMO }}
          # ClientId of the Azure Service principal
          client-id: ${{ secrets.AZ_RG_DV_GITHUB_TEST_DEMO_CLIENT_ID }}          
          # Azure subscriptionId
          subscription-id: $subscription_id
          
      - name: Deploy Azure Resource Manager (ARM) Template
        uses: Azure/arm-deploy@v1
        with:
          scope: subscription
          region: $location
          resourceGroupName: $resource_group_name
          template: '$GITHUB_WORKSPACE/src/template.json'
          deploymentMode: Incremental
          parameters: '$GITHUB_WORKSPACE/src/parameters.json'
