
name: CICD

on:

  push:
    branches: [ main, feature/add-ci-cd ]
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  azure_deploy:
    runs-on: ubuntu-latest
    environment: Staging
    steps:
      - uses: actions/checkout@v2
      
      - name: Diagnostics
        run: |
          pwd
          ls

      # - name: Install jq
      #   run: sudo apt-get install jq

      - name: Replace parameter values in parameters.json
        run: |
          echo ===== Before ======
          cat 'src/parameters.json'
          jq '.parameters.connections_logicapp_keyvault_name.value |= "${{ secrets.AZ_RG_DV_CONNECTION_NAME }}"' src/parameters.json
          jq '.parameters.vaults_key_vault_name.value |= "${{ secrets.AZ_RG_DV_KEYVAULT_NAME }}"' src/parameters.json
          jq '.parameters.workflows_lock_default_branch_name.value |= "${{ secrets.AZ_RG_DV_LOGICAPP_NAME }}"' src/parameters.json
          jq '.parameters.strings_personal_access_token.value |= "${{ secrets.INTPLUS_GITHUB_APP_SECRET }}"' src/parameters.json
          echo ====== After ======
          cat 'src/parameters.json'

      # Login to Azure
      - name: Azure Login
        uses: Azure/login@v1.4.3
        with:
          # Secret of the Azure Service principal
          creds: ${{ secrets.AZ_RG_DV_GITHUB_TEST_DEMO }}
          # ClientId of the Azure Service principal
          client-id: ${{ secrets.AZ_RG_DV_GITHUB_TEST_DEMO_CLIENT_ID }}          
          # Azure subscriptionId
          subscription-id: ${{ github.event.inputs.subscription_id }}
          
      - name: Deploy Azure Resource Manager (ARM) Template
        uses: Azure/arm-deploy@v1
        with:
          scope: subscription
          region: ${{ secrets.AZ_RG_DV_LOCATION }}
          resourceGroupName: ${{ secrets.AZ_RG_DV_RESOURCE_GROUP }}
          template: 'src/template.json'
          deploymentMode: Incremental
          parameters: 'src/parameters.json'
