
name: CICD

on:

  push:
    branches: [ main, feature/add-ci-cd ]
  pull_request:
    branches: [ main ]

jobs:
  azure_deploy:
    runs-on: ubuntu-latest
    environment: Staging
    steps:
      - uses: actions/checkout@v2
      
      - name: Replace parameter values in parameters.json
        run: |
          jq '.parameters.connections_logicapp_keyvault_name.value |= "${{ secrets.AZ_RG_DV_CONNECTION_NAME }}"'  src/parameters.json >  src/parameters_new.json
          jq '.parameters.vaults_key_vault_name.value |= "${{ secrets.AZ_RG_DV_KEYVAULT_NAME }}"' src/parameters_new.json >  src/parameters.json
          jq '.parameters.workflows_lock_default_branch_name.value |= "${{ secrets.AZ_RG_DV_LOGICAPP_NAME }}"' src/parameters.json > src/parameters_new.json
          jq '.parameters.strings_personal_access_token.value |= "${{ secrets.INTPLUS_GITHUB_APP_SECRET }}"' src/parameters_new.json >  src/parameters.json

      # Login to Azure
      - name: Azure Login
        run: az login --service-principal -u ${{ secrets.AZ_RG_DV_GITHUB_TEST_DEMO_CLIENT_ID }} -p ${{ secrets.AZ_RG_DV_GITHUB_TEST_DEMO }} --tenant ${{ secrets. AZ_RG_DV_TENANT_ID }}
      
      # Deploy template
      - name: Deploy Azure Resource Manager (ARM) Template
        run: |
          az group create --name ${{ secrets.AZ_RG_DV_RESOURCE_GROUP }} --location ${{ secrets.AZ_RG_DV_LOCATION }} --subscription ${{ secrets.AZ_RG_DV_SUBSCRIPTION }}
          az deployment group create --resource-group ${{ secrets.AZ_RG_DV_RESOURCE_GROUP }} --mode Incremental --parameters src/parameters.json --template-file src/template.json

